### ISSUE TITLE
2 node groups for user deployments

### ISSUE THREAD

**Issue by asmacdo** [dandi/dandi-hub#105]
1 Node group for gpu based,  1 Node group for non-gpu based

@satra Whats the use case for this? What actions do we need to be able to perform? 

(IMO) Personally, I'd like as few of the "knobs" as possible to be inside the aws console, maybe we could use a github action instead? The current setup doesn't use node groups for this, there may be better ways to perform those actions using labels or something.

**Comment by satra** [comment]
the use case is when someone requested a profile with a gpu it would scale up the gpu instance group and similarly for the other one for non-gpu profiles. in current dandihub you couldn't autoscale mixed instances easily, so having two instance groups helped with that.  and both instance groups were run with spot pricing and we could set k8s labels that were then used in selecting from the jupyterhub profile

i don't see how you prevent a gpu instance node from being instantiated without the labels associated with the instance groups. but if there is a way to achieve the same functionality with one, i would be fine with that. i just don't want pricier instances started when not required.

i didn't quite follow what you mean by inside the aws console?

**Comment by asmacdo** [comment]
FOr the new setup, Karpenter controls the autoscaling automatically. I'm going to close for now, since I don't think this will be relevant anymore, but we can reopen if there are issues.

**Comment by satra** [comment]
@asmacdo - i still don't understand what prevents the system from selecting a GPU node to start when asking for a non-GPU pod. it's the negation operator that i'm not sure about. can you describe how the system spins up a CPU node. also can you point to the node instance types that are potentially spun up?

**Comment by asmacdo** [comment]
GPU-based Node pool is auto-scaled by the nvidia operator. 
CPU only node pool is auto-scaled by karpenter, and the instance types are listed in the [karpenter config](https://github.com/dandi/dandi-hub/blob/do-eks/helm/karpenter-resources/values.yaml)

Each machine option for users (defined in profileList) will specify a Node Selector, for example:

```
node_selector:
    NodePool: gpu-ts # TIME-SLICING: Use this config with time-slicing mode
```

I may be missing something, but IIUC, we should be able to simply define our profileList, and let controllers/operators do all of the autoscaling.

**Comment by satra** [comment]
> I may be missing something, but IIUC, we should be able to simply define our profileList, and let controllers/operators do all of the autoscaling.

i hope so. it's the **not choosing of a GPU node for a CPU profile** part that i don't know if it is capable of doing.
