### ISSUE TITLE
Unable to see files in the `~/dandisets` directory

### ISSUE THREAD

**Issue by kabilar** [dandi/dandi-hub#109]
When I try to view the contents of the `/home/jovyan/dandisets/*/` directories, no files seem to exist.  See screenshot below.  Thank you.

![image](https://github.com/dandi/dandi-hub/assets/871137/fb7aa77a-62e5-4567-873c-6acd49aa6a53)

**Comment by satra** [comment]
do `datalad install .` inside that directory. to speed startup, we just install the super dataset without going through the entire tree. (as this happens during pod startup).

**Comment by kabilar** [comment]
Thanks @satra.  That makes sense.  I misread the [startup script](https://github.com/dandi/dandi-hub/blob/f14ccdda524ee573fd28512791826f8a13ddd78a/config.yaml.j2#L272) command: `datalad install https://github.com/dandi/dandisets`.  I now see that `-r` is not included but is described in the readme `~/dandisets` directory readme.
