### ISSUE TITLE
Parameterize Auth

### ISSUE THREAD

**Issue by asmacdo** [dandi/dandi-hub#131]
Dandihub extends [GitHub OAuth](https://github.com/dandi/dandi-hub/blob/do-eks/helm/jupyterhub/dandihub.yaml#L10). Rather than check user membership in GitHub orgs, it makes a call to the Dandi API. 

If BICAN and LINC have similar API servers setup, then all we need to do is parameterize [the api domain](https://github.com/dandi/dandi-hub/blob/do-eks/helm/jupyterhub/files/dandi_authenticator.py#L39)

**Comment by kabilar** [comment]
Thanks Austin.  LINC has the same API server setup as DANDI.
