### ISSUE TITLE
Review the DoEKS implementation with the team

### ISSUE THREAD

**Issue by kabilar** [dandi/dandi-hub#139]
## Description
Following up from yesterday's Slack thread of the phased approach for the DANDI Hub refactor, @asmacdo lets plan to review the DoEKS implementation with the team before we launch into production.  Let's find a time meet with @satra @yarikoptic @aaronkanzer (and anyone else who is interested) after April 8.

## Requirements
1. Describe the DoEKS system architecture (with a diagram)
2. Review the entire DoEKS codebase
3. Demonstrate how updates and new instances are deployed
4. Describe the security implications of the DoEKS design
5. Describe the cost implications of the DoEKS design
6. Describe the maintenance implications of the DoEKS design

**Comment by kabilar** [comment]
Added requirement 6 to the above list.

**Comment by yarikoptic** [comment]
FWIW I am still traveling/busy this week, can do after 14th.
