### ISSUE TITLE
satra/dandihub:e3b52ec0 image too big?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-hub#14]
trying to start a tiny issue on hub.  http://hub.dandiarchive.org/hub/spawn-pending/yarikoptic is either taking too long (minutes) 
![image](https://user-images.githubusercontent.com/39889/117029319-88998380-accc-11eb-900d-cf373c54d0bc.png)

NB it did finish eventually

`docker pull`ing on a hefty/speedy smaug shows that some layers are huge (>=600MB)... and actually I even ran out of space
(on smaug)

```
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /opt/conda/envs/ros3/lib/python3.9/ensurepip/_bundled/setuptools-49.2.1-py3-none-any.whl: no space left on device
```

not entirely sure why yet since
```
$> df /opt -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/md0        147G  125G   15G  90% /
```

https://hub.docker.com/r/satra/dandihub/tags?page=1&ordering=last_updated says it is 3.6GB .

I wonder if it couldn't be minimized -- sounds like too big FWIW

**Comment by yarikoptic** [comment]
FWIW, was eyeballing free space while redoing the pull -- never went below 7GB still available. So not entirely sure what is going on here but I reliably can't pull on smaug.

**Comment by satra** [comment]
the image has multiple environments. a normal one with dandi, an allensdk environment, and a streaming environment. also it's built on the jupyter datascience base, which includes Python, Julia, and R.

**Comment by yarikoptic** [comment]
FTR: and the 
```
jupyter/datascience-notebook          016833b15ceb        1fb531b11821        3 months ago        3.91GB
```
so it is huge already  but at least "runs" for me

**Comment by satra** [comment]
i think that's the uncompresed size. the uncompressed size for dandi is:

`dandiarchive/dandihub   latest    d60f907f233b   31 hours ago   12.8GB`

**Comment by satra** [comment]
so we should do some tweaking and optimization.

**Comment by satra** [comment]
i'm going to close this. the image is a little smaller now. but each conda environment also installs itk a dependency for nwbwidgets (which is 1G in size uncompressed). so that alone adds to it. i've revamped the creation to minimize the size per layer, but they are still large.
