### ISSUE TITLE
Push to production

### ISSUE THREAD

**Issue by asmacdo** [dandi/dandi-hub#154]
- [x] Determine which remaining phase1 issues are blocking 
- [x] Pick a date (1 week ahead)?
- [x] Email users: [DRAFT] On ___ we will have a planned downtime of ____ while we bring up an upgraded jupyterhub. While we plan to migrate the data stored in the home directory of hub instances, please be reminded that home storage  is not guaranteed to be permanent. The upgraded hub includes a [selection of images, and a pathway to add new images with specific environments pre-installed.](https://www.dandiarchive.org/handbook/50_hub/#custom-server-image) 
- [x] Bring up hub-staging and handtest
- [x] [Migrate home dir data OR use existing EFS](https://github.com/dandi/dandi-hub/issues/153)
- [x] Redirect hub.dandiarchive.org -> do-eks 
- [ ] Bring down ansible-deployment

**Comment by kabilar** [comment]
The last item is now tracked in #181.  Thanks Austin.  Great work.
