### ISSUE TITLE
[BICAN]Upgrade k8s (1.27 is EOL July 24)

### ISSUE THREAD

**Issue by asmacdo** [dandi/dandi-hub#165]
In the EKS dashboard "Upgrade Now" is there, but we should test prior in case any of the underlying libraries make use of removed APIs. https://kubernetes.io/blog/2023/08/15/kubernetes-v1-28-release/#feature-graduations-and-deprecations-in-kubernetes-v1-28

**Comment by asmacdo** [comment]
Also, lets create a procedure for how to do this.

**Comment by asmacdo** [comment]
LINC is finished. 

We did not establish a k8s upgrade procedure, since the previous deployment of LINC was pretty far behind the current main branch. There were differences in remote tf state, locking, environment separation, variables/overrides, and aws permissions. So instead, we just ported the LINC setup to a new deployment, which is now live.

**Comment by kabilar** [comment]
Thank you

**Comment by asmacdo** [comment]
When beginning the process to upgrade BICAN, I noticed it had not been getting used, so I took it down. 

When the readme addition merges, this will close as complete.
