### ISSUE TITLE
Dandihub Down?

### ISSUE THREAD

**Issue by rcpeene** [dandi/dandi-hub#175]
Going to https://hub.dandiarchive.org/ for me yields 'this site can't be reached :( (DNS_PROBE_FINISHED_NXDOMAIN)'
Is this only for me?

**Comment by kabilar** [comment]
Hi @rcpeene, thanks for the report.  Yes, the hub has been taken down while we are performing an upgrade.  It should be back online tomorrow.  We will send out an email when it is back up.

**Comment by kabilar** [comment]
Hi @rcpeene, the DANDI Hub service has now been restored.
