### ISSUE TITLE
Add branch protection rules for `main`

### ISSUE THREAD

**Issue by kabilar** [dandi/dandi-hub#185]

**Comment by asmacdo** [comment]
+1 (I don't have permission to do this)

IMO we should:
 - Restrict deletions
 - Require a Pull Request (0 reviews enforced but we should typically get at least 1)
 - block force pushes

**Comment by kabilar** [comment]
Thanks @asmacdo.  Just made you admin on the repo.

**Comment by asmacdo** [comment]
Done

**Comment by kabilar** [comment]
Thank you
