### ISSUE TITLE
cannot launch desktop anymore

### ISSUE THREAD

**Issue by satra** [dandi/dandi-hub#206]
launches (without any terminal appearing) and then gives a 500 error.

**Comment by kabilar** [comment]
Thanks for the report, Satra.  What instance type did you choose?  I was able to successful launch the desktop on `Base`.

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/e185a406-68fa-4e7d-9edf-0a98ce47a323">

**Comment by satra** [comment]
works fine after deleting a bunch of the folders.
