### ISSUE TITLE
Request to create an on-demand profile for ABDS workshop

### ISSUE THREAD

**Issue by kabilar** [dandi/dandi-hub#210]
Hi @asmacdo, 

@bendichter is requesting a temporary on-demand profile for the ABDS workshop on Friday, December 13.  Could you please create one similar to how you created one for Jeremy's workshop at MIT?

Requirements:

1. Name: `ABDS Workshop`
2. Features: Similar to the current [Base profile](https://github.com/dandi/dandi-hub/blob/aa9421d30d9ecbd5a65007682b7b5a61f18da5f8/envs/shared/jupyterhub.yaml#L86-L109) limits/guarantees, except that it provides on-demand instances.
3. Duration: Enable on Thursday ~4pm CST and disable on Friday at ~4pm CST.

**Comment by asmacdo** [comment]
@kabilar will do

**Comment by bendichter** [comment]
The timing on this is being shifted around. It's not clear yet when it will be. I will let you know when we have a set time.

**Comment by asmacdo** [comment]
@bendichter are we still looking at this week?

**Comment by bendichter** [comment]
Now it's looking like Tuesday of next week

**Comment by kabilar** [comment]
Hi @bendichter, is the workshop confirmed for Tuesday?

**Comment by bendichter** [comment]
Yes, would it be possible to turn on On Demand pricing?

**Comment by bendichter** [comment]
It did (see issue https://github.com/dandi/dandi-hub/issues/217), but it would be nice to ramp up on demand pricing for the rest of the event if possible (for the next 4 days)

**Comment by asmacdo** [comment]
It should be up now. Im testing the on-demand profile to be sure.

**Comment by asmacdo** [comment]
Correct. And my server started up as expected.

**Comment by kabilar** [comment]
Re-opening this issue to remind us to take down the profile.

**Comment by asmacdo** [comment]
@bendichter What time will you be done today?

**Comment by bendichter** [comment]
Go ahead and shut it off

**Comment by asmacdo** [comment]
done
