### ISSUE TITLE
Update dandihub deployment to use `latest-base` image

### ISSUE THREAD

**Issue by kabilar** [dandi/dandi-hub#215]
Hi @asmacdo,

In #212, the `Dockerfile` image tag was renamed from `latest` to `latest-base`.  Please update the dandihub deployment to implement this change.  Thanks.

**Comment by asmacdo** [comment]
@kabilar sure. Last time @aaronkanzer and I deployed Linchub there was a problem that caused that hub to go down briefly. That problem was solved and merged, but out of caution I'll wait until after hours today to run the update, unless you need it sooner.

**Comment by kabilar** [comment]
> @kabilar sure. Last time @aaronkanzer and I deployed Linchub there was a problem that caused that hub to go down briefly. That problem was solved and merged, but out of caution I'll wait until after hours today to run the update, unless you need it sooner.

Thanks @asmacdo.  That sounds good.

**Comment by kabilar** [comment]
Found a way to keep the previous tag of `latest` so no need for this change.  Will open a pull request shortly.
