### ISSUE TITLE
Spot Instance Reliability Issues During Tutorial - Need Discussion on JupyterHub Scalability

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-hub#217]
![Screenshot 2024-12-17 162434](https://github.com/user-attachments/assets/c271bb10-e5d7-458c-8c4f-32e962641a2c)

During a recent tutorial session, approximately 6-7 attendees using spot pricing were simultaneously disconnected from their instances. This incident mirrors similar reliability issues we observed in July, suggesting this remains an ongoing concern with spot instance stability.

The immediate impact was a disrupted tutorial session where multiple users lost their work environments simultaneously. While switching to on-demand pricing would provide better reliability for tutorials, this raises broader questions about DANDI Hub's scalability as a research platform. If the system becomes unstable with just 6-7 concurrent spot-priced users, this could present significant challenges for larger-scale research applications and prevent us from reaching a base of persistent active users. While we may have encountered unusually high demand during this session, the frequency of instance terminations could seriously impede scientific investigations if the platform were to scale up. This warrants further investigation into spot instance termination patterns, current load balancing strategies, and conditions that may affect spot instance reliability.

Some potential solutions worth exploring include implementing automatic failover to on-demand instances for tutorial sessions, and setting up monitoring to better understand termination patterns.

**Comment by asmacdo** [comment]
@bendichter this happened because I was upgrading restarting for the workshop.

**Comment by bendichter** [comment]
oh, ok. So creating the new profile requires a restart? Would there be a way to avoid that? Or at least would there be a way to indicate what is happening to active users?

**Comment by asmacdo** [comment]
Not usually, but there was a k8s upgrade also. AFAIK, no I don't think we have any way to indicate to users. We probably should schedule downtime for k8s upgrades in the future.
