### ISSUE TITLE
can we add the dandi package to the NWBstream environment?

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-hub#24]

**Comment by satra** [comment]
with the pynwb 2.0 release, i just pushed an update. the default environment (left most icon) now contains everything. should be the first icon. i don't know yet, why the other icons are not disappearing (looking into it).  no need to switch envs, etc.,.

you will need to kill your server and start it again to see the changes.

**Comment by satra** [comment]
in order to remove the old broken kernels, one needs to do:

```
$ rm -rf  .local/share/jupyter/kernels/dandi/
$ rm -rf  .local/share/jupyter/kernels/ros3
```

i have added this to the startup script, so should automatically remove those environments from user profiles when one logs back in after shutting down the server.
