### ISSUE TITLE
Provide ability to start/monitor your own HPC in the cloud

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-hub#25]
I guess should be done after we provide "pay for compute" facility for better integration etc.

But possibly we could just use [reproman](http://reproman.repronim.org/) for now (and/or in the future) -- just have it installed, test-drive on sample use cases, and improve/adjust.

**Comment by asmacdo** [comment]
I agree this is desirable, but I don't think there is a reasonable path forward in Kubernetes. 

I'm going to close, but feel free to reopen if there are new developments that make this possible.
