### ISSUE TITLE
Automatically mint/set/provide a token/credential for a user to authenticate to github

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-hub#35]
for `git push` etc.

I have not found any hit in search for `token` which might relate, although I thought we had that discussion before, and @dnkennedy was eager to get that for the ReproHub (which is based on older ABCD/ , which has common base with this hub in 2020.

**Comment by yarikoptic** [comment]
meanwhile we should probably provide in our default config result of something like
```
git config credential.helper 'cache --timeout=300'
```
so users at least have it cached to not enter over and over again for a bit

**Comment by satra** [comment]
dandihub has the token in an environment variable. however, this is not enabled in reprohub, since it is using vanilla github authentication for now. we could enable the custom authenticator to support this.
