### ISSUE TITLE
sudo password

### ISSUE THREAD

**Issue by djarecka** [dandi/dandi-hub#46]
@satra - I again have problem with permission when allocating the ports, this time using `singularity-compose`:

(sing_comp) jovyan@jupyter-djarecka:~/spyglass_test$ singularity-compose up
[sudo] password for jovyan: 
Sorry, try again.

**Comment by satra** [comment]
did you try compiling the container with suid option?

**Comment by djarecka** [comment]
also I've tried to use `options: fakeroot`, so I think I do not have to be root, but I still don't know what password I should use (`jupyter` doesn't work)

**Comment by satra** [comment]
> you mean the main DandiHub container?

yes, check the apptainer compilation flags and replace the without suid to with suid and then try.

and the base containers do not have a password set.

**Comment by djarecka** [comment]
> > you mean the main DandiHub container?
> 
> yes, check the apptainer compilation flags and replace the without suid to with suid and then try.
ok, you mean apptainer in the container. I've created a PR if you think that we can change it in the Hub. 
I've tried to test the containers locally but I'm failing (I slacked you in case you tried to run the container locally).

> 
> and the base containers do not have a password set.
but it expects something from me, complains when I leave it empty
