### ISSUE TITLE
README dead link

### ISSUE THREAD

**Issue by asmacdo** [dandi/dandi-hub#48]
Dead link near the top of the readme: [this blog post on autoscaling and spot pricing](https://www.replex.io/blog/the-ultimate-guide-to-deploying-kubernetes-cluster-on-aws-ec2-spot-instances-using-kops-and-eks#walkthrough)

**Comment by djarecka** [comment]
thank you for letting us know.

@satra - do you have any other link that we can use, or I should just remove the broken one?

**Comment by satra** [comment]
you can use a copy from the internet archive: https://web.archive.org/web/20220127043940/https://www.replex.io/blog/the-ultimate-guide-to-deploying-kubernetes-cluster-on-aws-ec2-spot-instances-using-kops-and-eks
