### ISSUE TITLE
[Bug]: No browser in remote desktop

### ISSUE THREAD

**Issue by CodyCBakerPhD** [dandi/dandi-hub#61]
Trying to use the internet browser through the remote desktop errors out as below

https://user-images.githubusercontent.com/51133164/217858933-9bf4a9e2-cbcc-41c5-8820-533d360ffe60.mp4

**Comment by satra** [comment]
working on it - the way to install firefox changed.

**Comment by satra** [comment]
this has been fixed, but i had to replace firefox with brave.
