### ISSUE TITLE
desktop login screen

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-hub#74]
I left the desktop inactive for a few minutes. When I came back I saw this screen:

<img width="865" alt="image" src="https://user-images.githubusercontent.com/844306/229828277-ebdac1ba-f06f-4ed0-9bc8-709a32a7d203.png">

Is there any way for me to sign in? If not, can we disable this locking feature?

**Comment by bendichter** [comment]
Clicking the Desktop button from the Launcher takes me back to this sign-in screen. I guess I'll need to restart the server.

**Comment by satra** [comment]
see the resolution in this comment: https://github.com/dandi/dandi-hub/issues/44#issuecomment-1369105088 

we cannot easily disable this automatically.
