### ISSUE TITLE
DANDIset data not visible in dandiset folder on DANDIHub

### ISSUE THREAD

**Issue by aranega** [dandi/dandi-hub#75]
It seems that the DANDIset data are not visible in the `dandiset` folders.
This behavior is equivalent on all containers related to all images (the default/base one, the GPU and the MATLAB one). 

We are not sure from where comes the problem, but we suspect that either the remote folder where the DANDIset data are cloned is not sync/cloned properly (only the "root" metarepository is cloned, not each subrepository), or that the [dandi-io plugin](https://github.com/balbasty/dandi-io/) is failing. 

This impacts all the containers started for any docker image of this repository.

Please find here two videos that shows that the `dandiset` subfolders do not contains any data in the base image/container and in the GPU container.

https://user-images.githubusercontent.com/2317394/234295462-ddf46b05-e31f-42b0-96f2-b065d074e002.mp4

https://user-images.githubusercontent.com/2317394/234295472-9bda02cd-9cc5-44e8-aa0d-a3b144224bfb.mp4

**Comment by gidili** [comment]
Thanks @aranega for the exposition and videos; @satra any idea who handles that part or who can help troubleshoot this?

**Comment by satra** [comment]
the hub only installs a datalad metadataset, which is a bare listing of dandisets. to actually populate them, one needs to execute `datalad install <dandiset-id>` in the dandisets directory. and then fetch any relevant files with `datalad get`. once done the files can be dropped `datalad drop`. 

the current intent is not that the dandiset is fully mounted and available as bytes. we may consider that in some other way in the near future.  

@yarikoptic - just noting here that it may be possible to use the fuse mount system on the hub with datalad to provide full capabilities.

**Comment by aranega** [comment]
Thanks @satra sorry for the late answer, I thought the ticket was closed already :sweat_smile:
