### ISSUE TITLE
Out of space on k8s?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-hub#80]
Tried to start tiny instance , got 

![image](https://github.com/dandi/dandi-hub/assets/39889/72e9c994-3e9c-4ab2-bc42-777813c29bb9)

**Comment by CodyCBakerPhD** [comment]
I just spawned a tiny just fine 🤔

**Comment by satra** [comment]
could be a temporary glitch. let's reopen if this reoccurs.
