### ISSUE TITLE
Use existing ansible role for kops?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-hub#81]
With @asmacdo we looked at https://github.com/Flaconi/ansible-role-kops/ which seems to be quite thorough and might help to  1. modularize kops definition, 2. avoid manual logic for installing etc which we have in our spagetti ansible file (partially modularized by WiP #76 )

**Comment by kabilar** [comment]
Hi @asmacdo, should we close this issue now that you are implementing the DoEKS version and not using ansible?
