### ISSUE TITLE
Move out more of jupyterhub config.yaml into configurable items

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-hub#82]
- `admin_users` (now me satra et al): https://github.com/dandi/dandi-hub/blob/dandi/config.yaml.j2#LL110C7-L110C18 
- ...

**Comment by asmacdo** [comment]
admin_users is configurable following df56d3b1946bfe4de412a66c381945a290b59157

Also I've parameterized HUB_DEPLOYMENT_NAME (ie dandihub vs linc vs bican) 

Added region param to the README

I'm going to close as completed, but if there are more vars that need to be parameterized, please file one for each (ie https://github.com/dandi/dandi-hub/issues/131)
