### ISSUE TITLE
Last modified dates incorrect

### ISSUE THREAD

**Issue by rcpeene** [dandi/dandi-hub#85]
I'm using dandihub, and I noticed the *last modified* date for several NWB files shows "3 years ago", which happens to be very incorrect.
I'm pretty sure these files were downloaded recently.

![Capture](https://github.com/dandi/dandi-hub/assets/23059582/8677ad95-b5ac-4a2b-8a40-9cd0f52a5ceb)

**Comment by CodyCBakerPhD** [comment]
What is the 'file_created_date' from the NWBFile metadata (I think it's under 'general')? Also what is the 'last modified date' from the asset metadata on DANDI?

Let me know if you're unsure how to find those out

**Comment by yarikoptic** [comment]
files in that dataset were indeed uploaded to DANDI 3 years ago:

```
dandi@drogon:/mnt/backup/dandi/dandisets/000021/sub-730756767$ git log .
commit e2a16977a9d863f3404dea5adb1a99e8ccd50d0f
Author: DANDI Meta-user <dandi@mit.edu>
Date:   Tue May 26 01:14:41 2020 -0700

    Ran backups2datalad.py
    
    214 files added
```

or see metadata record blobDateModified field at https://api.dandiarchive.org/api/dandisets/000021/versions/draft/assets/58703c97-c0a9-4736-b684-73c85c1a444a/ for a sample file.  While uploading - we check mtime for the files and set blobDateModified metadata field for them and then downloading a "good client" would set it to the last known date of file modification, which is what you got. So even if you downloaded them today, you would get files mtimes as of original mtime known for them.

So all is good and working as it should IMHO
