### ISSUE TITLE
Ensure License is handled appropriately

### ISSUE THREAD

**Issue by asmacdo** [dandi/dandi-hub#99]
The [do-eks branch](https://github.com/dandi/dandi-hub/tree/do-eks) will be the future of this repo.

This issue is to ensure that the code copied from https://github.com/awslabs/data-on-eks is handled appropriately and reflected in the license.

**Comment by asmacdo** [comment]
https://github.com/awslabs/data-on-eks/issues/475

**Comment by yarikoptic** [comment]
It says that 

💼 License
This library is licensed under the Apache 2.0 License.

and ours is too according to https://github.com/dandi/dandi-hub/blob/dandi/LICENSE  . So it is just a matter of stating copyright for those files copied to reflect original copyrights

**Comment by asmacdo** [comment]
Added a comment to the top of each copied file.
